const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PRODUCT = "GET_PRODUCT";
const GET_CATEGORIES = "GET_CATEGORIES";
const GET_CATEGORY = "GET_CATEGORY";
const GET_IMAGES = "GET_IMAGES";

const ADD_PRODUCT = "ADD_PRODUCT";

export {
  GET_PRODUCTS,
  GET_CATEGORIES,
  GET_CATEGORY,
  GET_PRODUCT,
  GET_IMAGES,
  ADD_PRODUCT,
};
