const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PRODUCT = "GET_PRODUCT";
const GET_CATEGORIES = "GET_CATEGORIES";
const GET_PRODUCTS_CATEGORY_ID = "GET_PRODUCTS_CATEGORY_ID";
const GET_IMAGES = "GET_IMAGES";

const REMOVE_CATEGORY_ID = "REMOVE_CATEGORY_ID";
const GET_NEXT_PRODUCTS = "GET_NEXT_PRODUCTS";

const ADD_PRODUCT = "ADD_PRODUCT";
const REMOVE_PRODUCT = "REMOVE_PRODUCT";
const REMOVE_ALL_PRODUCTS = "REMOVE_ALL_PRODUCTS";
const REMOVE_ALL_PRODUCT = "REMOVE_ALL_PRODUCT";

export {
  GET_PRODUCTS,
  GET_CATEGORIES,
  GET_PRODUCTS_CATEGORY_ID,
  GET_PRODUCT,
  GET_IMAGES,
  ADD_PRODUCT,
  REMOVE_PRODUCT,
  REMOVE_ALL_PRODUCTS,
  REMOVE_ALL_PRODUCT,
  REMOVE_CATEGORY_ID,
  GET_NEXT_PRODUCTS,
};
